id = "noteboks"
name = "noteboks"
version = "0.0.2"
schema_version = 1
authors = ["Zac Garby <me@zacgarby.co.uk>"]
description = "Noteboks support for Zed. Markdown-based note vault."
repository = "https://github.com/zac-garby/noteboks"

[grammars.noteboks_md_inline]
repository = "https://github.com/zac-garby/tree-sitter-markdown"
commit = "0877ff93208387fa38827db19b2fe0f111fcc9bf"

[language_servers.noteboks-lsp]
name = "Noteboks LSP"
languages = ["noteboks"]
